http:
  port: ${PORT}
apiEndpoints:
  internaljwt:
    host: '*'
    paths: ['/internaljwt', '/internaljwt/*']
  externaljwt:
    host: '*'
    paths: ['/externaljwt', '/externaljwt/*']
serviceEndpoints:
  backend:
    url: 'http://httpbin.org/'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt:
              issuer: express-gateway
              audience: something
              subject: test
              secretOrPublicKey: ssssst
              checkCredentialExistence: true
      - proxy: &httpBinConf
          - action:
              serviceEndpoint: backend
              changeOrigin: true
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: true
            secretOrPublicKeyFile: '/app/key.pem'
      - proxy: *httpBinConf
